name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - master

jobs:
  git-commit-info:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.set-commit-id.outputs.commit_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Commit ID for Tagging
        id: set-commit-id
        run: echo "commit_id=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  deploy-thinesh-app:
    needs: [git-commit-info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Thinesh Application to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: acrpcsregistry
          acrUsername: ${{ secrets.DOCKER_USERNAME }}
          acrPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: aca-identity-service
          containerAppEnvironment: managedEnvironment-PCSODCTEMP-81bc
          resourceGroup: ${{ secrets.RESOURCE_GROUP_NAME }}
          imageToBuild: acrpcsregistry.azurecr.io/thinesh-app:${{ needs.git-commit-info.outputs.commit_id }}
          dockerfilePath: ./Dockerfile
